require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'RNBuildVariants', {
  'DebugDev' => :debug,
  'DebugStaging' => :debug,
  'DebugProd' => :debug,
  'ReleaseDev' => :release,
  'ReleaseStaging' => :release,
  'ReleaseProd' => :release,
}

debugs = ['DebugDev', 'DebugStaging', 'DebugProd']

target 'RNBuildVariants' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RNBuildVariantsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: debugs)
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNBuildVariants-tvOS' do
  # Pods for RNBuildVariants-tvOS

  target 'RNBuildVariants-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
